class Tweets {
  // This was generated using ChatGPT
  static const List<String> tweets = [
    "Just discovered Google. How do I get back to it?",
    "Why do people call it 'surfing' the web? I'm not getting wet.",
    "Tried to Google 'how to Google'. Got stuck in a loop.",
    "My grandson said I need a profile pic. Does anyone have a spare Polaroid?",
    "What's an emoji? Is it like a hieroglyph?",
    "Someone sent me a GIF. It’s like a picture that won’t stay still!",
    "Just made a Facebook. Can I grow vegetables on it?",
    "Found something called a meme. Is it contagious?",
    "How do I print out a tweet? Asking for a friend.",
    "Got a friend request from someone named 'Spam'. Should I accept?",
    "My computer asked if I wanted to save my password. Save it where?",
    "Just posted my first selfie. Do I get a medal or something?",
    "What's a hashtag? Is it like a hash brown?",
    "Just downloaded an app. Not sure where it went.",
    "My grandson said I need to 'update' my software. Is it like a vaccination?",
    "Tried to search for a recipe online, ended up with 20 tabs open. Help!",
    "Just discovered YouTube. It’s like TV but with more cats!",
    "What's the deal with 'cookies'? Can I eat them?",
    "Tried to send an email, but it got stuck in the 'outbox'. Is it like being stuck in traffic?",
    "How do I 'stream' music? Do I need a river?",
    "My phone suggested I download Tinder. Is that a cooking app?",
    "Found a 'blog'. Is it like a diary, but for everyone to read?",
    "What's a 'WiFi'? Is it like Wi-Fi but spelled wrong?",
    "My grandson said to use a VPN. Is it like SPF for the internet?",
    "Just discovered Reddit. It’s like a rabbit hole with opinions!",
    "How do I 'mute' someone in real life? Asking for my wife.",
    "Tried to Skype, ended up staring at my own face. Awkward.",
    "Just joined Twitter. What's a 'retweet'? Do I get a bird?",
    "What's an 'influencer'? Do they influence the weather?",
    "My phone says 'low battery'. Can I plug it into my car?",
    "What's a 'podcast'? Is it like a radio show, but with more talking?",
    "Found out what a 'vlog' is. It's like a video diary. Do people really watch these?",
    "What's 'cloud storage'? Is it up in the sky?",
    "My computer asked if I wanted to install an 'update'. Can I just say no?",
    "Tried to join a 'Zoom' meeting. Ended up with my camera pointing at the ceiling.",
    "What's an 'algorithm'? Is it like a dance move?",
    "Just discovered Netflix. It's like a never-ending movie marathon!",
    "My grandson said to use 'incognito mode'. Is it like wearing a disguise?",
    "What's a 'Pinterest'? Is it like a bulletin board?",
    "Just sent my first tweet. Now what?"
  ];
}
